### ISSUE TITLE
need description

### ISSUE THREAD

**Issue by aravinthraj98** [Shalini-CEG/React-API-working#1]
update readme by detail description about this app

**Comment by Shalini-2209** [comment]
Nothing to write read me and all..😂
Itz a simple one..

**Comment by aravinthraj98** [comment]
HOS...just asked to give some details about repository.... like by seeing the code i can get it is a todo app..so mention that like "it is todo application using react js " so and so...because some fans like me🤭 will check your repo and get confused without details

**Comment by Shalini-2209** [comment]
😑Ok!
